### ISSUE TITLE
rights issue with furyctl

### ISSUE THREAD

**Issue by raclepoulpe** [sighupio/fury-getting-started#25]
**furyctl  version**
```console
INFO[0000] Furyctl version 0.9.0                        
INFO[0000] built 2022-12-22T10:49:22Z from commit 7f6d79938facf12f00d1ef4f53148a72c48f2d56 
```

**os-release**
```console
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Furyfile.yml**
```yaml
versions:
  monitoring: v2.0.1
  logging: v3.0.1
  ingress: v1.13.1

bases:
  - name: monitoring/prometheus-operator
  - name: monitoring/prometheus-operated
  - name: monitoring/alertmanager-operated
  - name: monitoring/grafana
  - name: monitoring/kubeadm-sm
  - name: monitoring/configs
  - name: monitoring/kube-state-metrics
  - name: monitoring/node-exporter

  - name: logging/opensearch-single
  - name: logging/opensearch-dashboards
  - name: logging/logging-operator
  - name: logging/logging-operated
  - name: logging/configs
  - name: logging/cerebro

  - name: ingress/nginx
  - name: ingress/cert-manager
  - name: ingress/forecastle
  ```

**How to reproduce**

As user with non-root rights:

```bash
$ furyctl vendor -H
```

Result : 

```console
ERRO[0000] error downloading 'file:///workspace/public-cloud-examples/examples/05/https:/oauth2:@github.com/sighupio/fury-kubernetes-logging.git?ref=v3.0.1': /usr/bin/git exited with 128: Cloning into '/tmp/getter2576474685/temp'... fatal: '/workspace/public-cloud-examples/examples/05/https:/oauth2:@github.com/sighupio/fury-kubernetes-logging.git' does not appear to be a git repository fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.  
ERRO[0000] error downloading 'file:///workspace/public-cloud-examples/examples/05/https:/oauth2:/sighupio/fury-kubernetes-logging.git?ref=v3.0.1': /usr/bin/git exited with 128: Cloning into '/tmp/getter3945610575/temp'... fatal: '/workspace/public-cloud-examples/examples/05/https:/oauth2: *******@github.com/sighupio/fury-kubernetes-logging.git' does not appear to be a git repository fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.  
(etc..)
```

**Workaround**

```bash
sudo furyctl vendor -H
sudo chown -R gitpod:gitpod vendor
```
